version: "3"
networks:
  default:
    external:
      name: gateway
  database:
    driver: bridge
    internal: true

services:
  index:
    build: .
    restart: on-failure
    image: southclaws/openmp-index
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/prisma?schema=public
      LOG_LEVEL: debug
    ports:
      - 8080:80
    networks:
      - default
      - database
    depends_on:
      - postgres
    labels:
      traefik.enable: "true"
      traefik.docker.network: gateway
      traefik.http.routers.omp_index.rule: Host(`index.open.mp`)
      traefik.http.routers.omp_index.entrypoints: https
      traefik.http.routers.omp_index.tls.certresolver: default
      com.centurylinklabs.watchtower.enable: "true"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_DIR}/openmp-index/postgres:/var/lib/postgresql/data
    networks:
      - database

  minio:
    image: minio/minio
    command: server /data
    restart: always
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - 8082:9000
    volumes:
      - ${DATA_DIR}/openmp-index/minio:/data
    networks:
      - default
    labels:
      traefik.enable: "true"
      traefik.docker.network: gateway
      traefik.http.routers.omp_index_minio.rule: Host(`assets.open.mp`)
      traefik.http.routers.omp_index_minio.entrypoints: https
      traefik.http.routers.omp_index_minio.tls.certresolver: default

  rabbit:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8081:80
    labels:
      traefik.enable: "true"
      traefik.docker.network: gateway
      traefik.http.routers.omp_index_pgadmin.rule: Host(`pgadmin.open.mp`)
      traefik.http.routers.omp_index_pgadmin.entrypoints: https
      traefik.http.routers.omp_index_pgadmin.tls.certresolver: default
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - default
      - database
